### ISSUE TITLE
"launch on start" feature does not work on Gnome 3.28.2

### ISSUE THREAD

**Issue by glaubersm** [flathub/com.github.bitseater.weather#1]
Title says by itself.
I use Arch Linux.

**Comment by TingPing** [comment]
It simply isn't possible for sandboxed applications to request autostarting atm.

**Comment by glaubersm** [comment]
do you know if there is a bug report in flatpak tracker about such issue?

**Comment by TingPing** [comment]
https://github.com/flatpak/flatpak/issues/118

**Comment by glaubersm** [comment]
Thank you very much.

**Comment by ghost** [comment]
Thanks @TingPing . I close the issue.
