### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by ghost** [flathub/com.github.bitseater.weather#2]
Pleased, delete this repo. Thanks.

**Comment by bilelmoussaoui** [comment]
What's going on with those guys???? 
@TingPing Please don't. I'm going to revert the latest commit and keep maintaining this app as I'm the one who published it first.

**Comment by TingPing** [comment]
@bilelmoussaoui Ok.

**Comment by TingPing** [comment]
You know where they moved the repo to? It will need a new app-id..

**Comment by barthalion** [comment]
https://gitlab.com/bitseater/meteo
