### ISSUE TITLE
Systray indicator doesn’t work in recent Gnome versions

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.github.bitseater.weather#5]
Please do not use tray indicators anymore, as you need special shell extensions for displaying these –, which is the case since for about two years already. Additionally, you could provide the option for placing them left/middle/right in the top bar, which would be very handy. See OpenWeather [0] for example.

[0] https://gitlab.com/jenslody/gnome-shell-extension-openweather

**Comment by bilelmoussaoui** [comment]
It's not the correct repo to report this. I tried to build the application without libappindicator but it seems to be not possible for now :/ Will send a patch upstream

**Comment by fbruetting** [comment]
Ok, I understand. And yeah, would be rad!
