### ISSUE TITLE
Duplicate flathub entry

### ISSUE THREAD

**Issue by dschier-wtd** [flathub/com.github.bitseater.weather#6]
# Issue Type

Bug

## Behaviour

The meteo app is duplicated on flathub

here:
- https://flathub.org/apps/details/com.github.bitseater.weather
- https://github.com/flathub/com.github.bitseater.weather

and here:
- https://flathub.org/apps/details/com.gitlab.bitseater.meteo
- https://github.com/flathub/com.gitlab.bitseater.meteo

## Expected behaviour

Either mark the old app as old in flathub and github or
remove the old app from falthub.

**Comment by bilelmoussaoui** [comment]
@TingPing You already marked this app as EOL?

**Comment by TingPing** [comment]
https://github.com/flathub/linux-store-frontend/issues/126
